// <auto-generated>
//   GENERATED by tools/generate-permissions.sh from the access-control manifest
//   (docs/access-control-matrix.json). DO NOT EDIT BY HAND.
//
//   To change permissions: edit the canonical matrix
//   (patient-care-super/docs/access-control-matrix.md), regenerate the manifest
//   (patient-care-super/tools/generate-access-manifest.sh), re-vendor
//   docs/access-control-matrix.json, then re-run tools/generate-permissions.sh.
//
//   Access-control manifest semantic hash: 16599d6c39fc
// </auto-generated>

namespace Neurocorp.Api.Web.Authorization;

/// <summary>
/// Compile-time constants for every Permission claim in the access-control matrix.
/// Use with <see cref="AuthPolicy.Permission(string)"/>:
/// <c>[Authorize(Policy = AuthPolicy.Permission(Permissions.AdminSitesManage))]</c>.
///
/// Generated from the manifest; <see cref="AccessControlManifest.SemanticHash"/> anchors the
/// version and AccessControlConformanceTests asserts this set equals the manifest's claims.
/// </summary>
public static class Permissions
{
    public const string AdminLookupsAppointmentStatusManage = "Admin.Lookups.AppointmentStatus.Manage";
    public const string AdminLookupsAppointmentStatusView = "Admin.Lookups.AppointmentStatus.View";
    public const string AdminLookupsPaymentTypeManage = "Admin.Lookups.PaymentType.Manage";
    public const string AdminLookupsPaymentTypeView = "Admin.Lookups.PaymentType.View";
    public const string AdminLookupsRoleTypeManage = "Admin.Lookups.RoleType.Manage";
    public const string AdminLookupsRoleTypeView = "Admin.Lookups.RoleType.View";
    public const string AdminLookupsSpecialtyTypeManage = "Admin.Lookups.SpecialtyType.Manage";
    public const string AdminLookupsSpecialtyTypeView = "Admin.Lookups.SpecialtyType.View";
    public const string AdminSitesManage = "Admin.Sites.Manage";
    public const string AdminSitesView = "Admin.Sites.View";
    public const string AdminUsersManage = "Admin.Users.Manage";
    public const string AdminUsersView = "Admin.Users.View";
    public const string AdminView = "Admin.View";
    public const string AppointmentsBook = "Appointments.Book";
    public const string AppointmentsProviderAmount = "Appointments.ProviderAmount";
    public const string AppointmentsReassign = "Appointments.Reassign";
    public const string AppointmentsView = "Appointments.View";
    public const string CaretakersEdit = "Caretakers.Edit";
    public const string CaretakersLinkPatient = "Caretakers.LinkPatient";
    public const string CaretakersView = "Caretakers.View";
    public const string DashboardPlanAlerts = "Dashboard.PlanAlerts";
    public const string DashboardProviderAmount = "Dashboard.ProviderAmount";
    public const string DashboardView = "Dashboard.View";
    public const string PatientsDelinquentView = "Patients.Delinquent.View";
    public const string PatientsEdit = "Patients.Edit";
    public const string PatientsLinkCaretaker = "Patients.LinkCaretaker";
    public const string PatientsStartDiscovery = "Patients.StartDiscovery";
    public const string PatientsView = "Patients.View";
    public const string PaymentsAdjust = "Payments.Adjust";
    public const string PaymentsRecord = "Payments.Record";
    public const string PaymentsRefund = "Payments.Refund";
    public const string PaymentsSplit = "Payments.Split";
    public const string PaymentsView = "Payments.View";
    public const string ScheduleBook = "Schedule.Book";
    public const string ScheduleRebook = "Schedule.Rebook";
    public const string ScheduleView = "Schedule.View";
    public const string ServicePaymentsAdjust = "ServicePayments.Adjust";
    public const string ServicePaymentsRecord = "ServicePayments.Record";
    public const string ServicePaymentsView = "ServicePayments.View";
    public const string StatementsCaretakerView = "Statements.Caretaker.View";
    public const string StatementsTherapistView = "Statements.Therapist.View";
    public const string StatementsView = "Statements.View";
    public const string SystemDiagnostics = "System.Diagnostics";
    public const string TherapistsDelinquentView = "Therapists.Delinquent.View";
    public const string TherapistsEdit = "Therapists.Edit";
    public const string TherapistsManageSpecialties = "Therapists.ManageSpecialties";
    public const string TherapistsView = "Therapists.View";
    public const string TreatmentPlansBook = "TreatmentPlans.Book";
    public const string TreatmentPlansEdit = "TreatmentPlans.Edit";
    public const string TreatmentPlansView = "TreatmentPlans.View";
}
