#!/usr/bin/env bash
# ============================================================================
# generate-permissions.sh  —  WP-17B-2 (API: permission constants codegen)
# ============================================================================
#
# Generates src/Web/Authorization/Permissions.g.cs FROM the access-control manifest
# (docs/access-control-matrix.json, vendored from patient-care-super — canonical
# source: patient-care-super/docs/access-control-matrix.md).
#
# Why generate: the matrix is the single source of truth (WP-17). Hand-typing claim
# strings into [Authorize(Policy = ...)] sites invites typos and drift; a generated
# constants class makes every policy reference a compiler-checked symbol, and CI
# (WP-17D) regenerates + fails on diff. AccessControlConformanceTests also asserts the
# constant set equals the manifest's claim set, so a missing/extra constant fails the build.
#
# Determinism: byte-identical across runs (claims come pre-sorted from the manifest;
# no timestamp in the output — only the manifest semantic hash in the header).
#
# Usage:
#   tools/generate-permissions.sh            (re)generate src/Web/Authorization/Permissions.g.cs
#   tools/generate-permissions.sh --check    regenerate to a temp file, diff against the
#                                            committed file; exit 1 on drift (for WP-17D CI)
#
# Exit codes: 0 ok/in-sync · 1 drift (--check) · 2 error
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$REPO_ROOT/docs/access-control-matrix.json"
OUT="$REPO_ROOT/src/Web/Authorization/Permissions.g.cs"
MODE="generate"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) MODE="check"; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

command -v jq >/dev/null 2>&1 || { echo "ERROR: jq is required" >&2; exit 2; }
[[ -f "$MANIFEST" ]] || { echo "ERROR: manifest not found: $MANIFEST" >&2; exit 2; }

# NB: pipe jq through `tr -d '\r'` everywhere — the Windows jq build emits CRLF, and a stray
# CR inside a generated C# string literal is read as a newline ("Newline in constant").
HASH="$(jq -r '._meta.semanticHash' "$MANIFEST" | tr -d '\r')"
[[ -n "$HASH" && "$HASH" != "null" ]] || { echo "ERROR: manifest has no semanticHash" >&2; exit 2; }

emit() {
  cat <<EOF
// <auto-generated>
//   GENERATED by tools/generate-permissions.sh from the access-control manifest
//   (docs/access-control-matrix.json). DO NOT EDIT BY HAND.
//
//   To change permissions: edit the canonical matrix
//   (patient-care-super/docs/access-control-matrix.md), regenerate the manifest
//   (patient-care-super/tools/generate-access-manifest.sh), re-vendor
//   docs/access-control-matrix.json, then re-run tools/generate-permissions.sh.
//
//   Access-control manifest semantic hash: $HASH
// </auto-generated>

namespace Neurocorp.Api.Web.Authorization;

/// <summary>
/// Compile-time constants for every Permission claim in the access-control matrix.
/// Use with <see cref="AuthPolicy.Permission(string)"/>:
/// <c>[Authorize(Policy = AuthPolicy.Permission(Permissions.AdminSitesManage))]</c>.
///
/// Generated from the manifest; <see cref="AccessControlManifest.SemanticHash"/> anchors the
/// version and AccessControlConformanceTests asserts this set equals the manifest's claims.
/// </summary>
public static class Permissions
{
EOF
  jq -r '.claims[] | .claim' "$MANIFEST" | tr -d '\r' \
    | while read -r claim; do
        name="$(printf '%s' "$claim" | tr -d '.')"
        printf '    public const string %s = "%s";\n' "$name" "$claim"
      done
  echo "}"
}

if [[ "$MODE" == "check" ]]; then
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' EXIT
  emit > "$tmp"
  if [[ ! -f "$OUT" ]] || ! diff -q "$OUT" "$tmp" >/dev/null; then
    echo "DRIFT: $OUT is out of date — re-run tools/generate-permissions.sh" >&2
    [[ -f "$OUT" ]] && diff -u "$OUT" "$tmp" >&2 || true
    exit 1
  fi
  echo "Permissions.g.cs is in sync with the manifest ($HASH)."
  exit 0
fi

emit > "$OUT"
echo "Generated $OUT from manifest $HASH ($(jq '.claims | length' "$MANIFEST") claims)."
