name: Build and Publish Patient Care API Docker Image

on:
  push:
    branches: [ main, features/aev/add-github-actions-capability ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.100'

    - name: Restore dependencies
      run: dotnet restore ./patient-care-api.sln  

    - name: Build
      run: dotnet build ./patient-care-api.sln --no-restore

    - name: Run tests
      run: |
        dotnet test ./patient-care-api.sln --no-build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/Dockerfile
        push: true
        tags: anibalvelarde/patient-care-api:latest

    - name: Clean up
      run: docker rmi anibalvelarde/patient-care-api:latest